export const ACTION_INCREMENT_COUNT = 'INCREMENT_COUNT';
export const ACTION_INCREMENT_COUNT_SUCCESS = 'INCREMENT_COUNT_SUCCESS';
export const ACTION_DECREMENT_COUNT = 'DECREMENT_COUNT';
export const ACTION_DECREMENT_COUNT_SUCCESS = 'DECREMENT_COUNT_SUCCESS';
